#' Collect citations
#'
#' @param path A single project directory (searched recursively) or a vector of
#'   files (.R/.Rmd/.Qmd).
#' @param ignore_unqualified_functions Character vector of function names to ignore when
#'   attributing (unqualified) calls to Stan packages. Defaults to exports from
#'   base R packages listed in `stdlib_funs()`. Calls like `rstan::plot()` will NOT
#'   be ignored even if `plot` is in `ignore_unqualified_functions`.
#' @param strict If `TRUE`, only count unqualified function calls that resolve
#'   to a single Stan package.
#' @param format One of "bibtex" or "bibentry".
#' @return A BibTeX character vector or a bibentry object.
#' @export
stan_cite <- function(
  path = ".",
  ignore_unqualified_functions = .stdlib_funs,
  strict = FALSE,
  format = c("bibtex", "bibentry")
) {
  scan_usage(
    path = path,
    ignore_unqualified_functions = ignore_unqualified_functions,
    strict = strict,
    allowed_packages = .stan_pkgs,
    export_index = .stan_export_index,
    origin_map = .stan_origin_map
  ) |>
    (\(usage) c(usage$packages, usage$functions, "stan", "stanflow"))() |>
    unique() |>
    mget(
      envir = .stan_citation_funs,
      inherits = TRUE,
      ifnotfound = list(NULL)
    ) |>
    Filter(Negate(is.null), x = _) |>
    (\(entries) {
      if (!length(entries)) {
        character()
      } else {
        entries <- do.call(what = c, args = entries)
        if (identical(match.arg(format, c("bibtex", "bibentry")), "bibentry")) {
          entries
        } else {
          toBibtex(entries)
        }
      }
    })()
}

#' Find used Functions and Packages
#'
#' The Stan values for `allowed_packages`, `export_index`, and `origin_map`
#' are generated by `data_raw/sysdata.R`.
#'
#' @inheritParams stan_cite
#' @param allowed_packages Character vector of package namespaces to attribute
#'   to Stan usage. Defaults to `.stan_pkgs`.
#' @param export_index Named list mapping function names to packages. Defaults
#'   to `.stan_export_index`.
#' @param origin_map Named character vector mapping `pkg::fun` keys to the
#'   origin package. Defaults to `.stan_origin_map`.
#' @return A list of packages, resolved functions, and ambiguous function calls.
#' @export
scan_usage <- function(
  path = ".",
  ignore_unqualified_functions = .stdlib_funs,
  strict = FALSE,
  allowed_packages = .stan_pkgs,
  export_index = .stan_export_index,
  origin_map = .stan_origin_map
) {
  paths <- normalizePath(path, winslash = "/", mustWork = TRUE)
  dir_flags <- dir.exists(paths)

  files <- if (length(paths) == 1L && dir_flags) {
    dir_path <- paths[[1L]]
    cli::cli_alert_info("Searching directory {.path {dir_path}}")
    list.files(
      dir_path,
      recursive = TRUE,
      full.names = TRUE,
      ignore.case = TRUE,
      pattern = "\\.(R|Rmd|Qmd)$"
    )
  } else {
    if (any(dir_flags)) {
      cli::cli_abort(
        "{.arg path} must be a single directory or a vector of files."
      )
    }
    paths |>
      (\(paths) {
        lapply(
          paths,
          \(file_path) cli::cli_alert_info("Searching {.path {file_path}}")
        )
        paths
      })()
  }

  if (!length(files)) {
    cli::cli_abort("No files found.")
  }

  hits <- unique(files) |>
    lapply(
      \(file) {
        file |>
          .extract_code() |>
          .scan_tokens(
            ignore_unqualified_functions = ignore_unqualified_functions,
            strict = strict,
            allowed_packages = allowed_packages,
            export_index = export_index,
            origin_map = origin_map
          )
      }
    )

  ambiguous <- .collect_unique(hits, "ambiguous")
  if (strict && length(ambiguous)) {
    cli::cli_abort(
      ambiguous |>
        (\(funs) paste0("{.code ", funs, "()}"))() |>
        paste(collapse = ", ") |>
        (\(calls) {
          paste0(
            "Cannot reliably detect which packages these functions are from: ",
            calls,
            ". Please namespace them ({.code pkg::function()}) and re-run stan_cite()."
          )
        })()
    )
  }

  structure(
    list(
      packages = .collect_unique(hits, "pkgs"),
      functions = .collect_unique(hits, "keys"),
      ambiguous = ambiguous
    ),
    class = "scan_usage"
  )
}

.collect_unique <- function(hits, field) {
  hits |>
    lapply(`[[`, field) |>
    unlist(use.names = FALSE) |>
    unique() |>
    sort()
}

.extract_code <- function(file) {
  ext <- file |>
    sub(".*\\.", "", x = _) |>
    tolower()
  if (ext == "r") {
    return(paste(readLines(file, warn = FALSE), collapse = "\n"))
  }

  tmp <- tempfile(fileext = ".R")
  on.exit(unlink(tmp), add = TRUE)

  if (ext == "rmd") {
    knitr::purl(file, tmp, quiet = TRUE, documentation = 0)
  } else if (ext == "qmd") {
    quarto::qmd_to_r_script(file, tmp)
  }

  paste(readLines(tmp, warn = FALSE), collapse = "\n")
}

.scan_tokens <- function(
  code,
  ignore_unqualified_functions,
  strict = FALSE,
  allowed_packages = .stan_pkgs,
  export_index = .stan_export_index,
  origin_map = .stan_origin_map
) {
  empty <- list(pkgs = character(), keys = character(), ambiguous = character())
  expr <- tryCatch(
    parse(text = code, keep.source = FALSE),
    error = function(e) NULL
  )
  if (is.null(expr)) {
    return(empty)
  }

  acc <- new.env(parent = emptyenv())
  acc$pos <- 0L
  acc$lib_pkgs <- character()
  acc$lib_pos <- integer()
  acc$lib_is_attach <- logical()
  acc$ns_pkgs <- character()
  acc$ns_keys <- character()
  acc$unqual_funs <- character()
  acc$unqual_pos <- integer()

  lib_funs <- c("library", "require", "requireNamespace")

  for (i in seq_along(expr)) {
    .ast_walk(
      expr[[i]],
      acc,
      ignore_unqualified_functions,
      lib_funs,
      allowed_packages
    )
  }

  lib_data <- if (length(acc$lib_pkgs)) {
    data.frame(
      pos = acc$lib_pos,
      pkg = acc$lib_pkgs,
      is_attach = acc$lib_is_attach,
      stringsAsFactors = FALSE
    )
  } else {
    NULL
  }

  resolved <- .resolve_candidates(
    list(funs = acc$unqual_funs, idx = acc$unqual_pos),
    lib_data,
    strict,
    allowed_packages,
    export_index,
    origin_map
  )

  list(
    pkgs = c(acc$lib_pkgs, acc$ns_pkgs, resolved$pkgs),
    keys = c(acc$ns_keys, resolved$keys),
    ambiguous = resolved$ambiguous
  )
}

.ast_walk <- function(
  x,
  acc,
  ignore_unqualified_functions,
  lib_funs,
  allowed_packages = .stan_pkgs
) {
  if (is.null(x)) {
    return(invisible(NULL))
  } else if (is.call(x)) {
    acc$pos <- acc$pos + 1L

    head <- x[[1L]]
    head_name <- if (is.symbol(head)) as.character(head) else NULL

    if (!is.null(head_name) && head_name %in% c("::", ":::")) {
      if (length(x) >= 3L) {
        pkg <- .ast_lit_name(x[[2L]])
        fun <- .ast_lit_name(x[[3L]])

        if (
          !is.null(pkg) &&
            !is.null(fun) &&
            pkg %in% allowed_packages
        ) {
          acc$ns_pkgs <- c(acc$ns_pkgs, pkg)
          acc$ns_keys <- c(acc$ns_keys, paste0(pkg, "::", fun))
        }
      }
    } else if (!is.null(head_name) && head_name == "use") {
      pkg <- .ast_get_lib_pkg(x)
      if (!is.null(pkg) && pkg %in% allowed_packages) {
        acc$ns_pkgs <- c(acc$ns_pkgs, pkg)
        funs <- .ast_get_use_funs(x)
        if (length(funs)) {
          acc$ns_keys <- c(acc$ns_keys, paste0(pkg, "::", funs))
        }
      }
    } else if (!is.null(head_name) && head_name %in% lib_funs) {
      pkg <- .ast_get_lib_pkg(x)
      if (!is.null(pkg) && pkg %in% allowed_packages) {
        acc$lib_pkgs <- c(acc$lib_pkgs, pkg)
        acc$lib_pos <- c(acc$lib_pos, acc$pos)
        acc$lib_is_attach <- c(
          acc$lib_is_attach,
          head_name != "requireNamespace"
        )
      }
    } else if (!is.null(head_name)) {
      if (!(head_name %in% ignore_unqualified_functions)) {
        acc$unqual_funs <- c(acc$unqual_funs, head_name)
        acc$unqual_pos <- c(acc$unqual_pos, acc$pos)
      }
    }

    if (is.call(head)) {
      .ast_walk(
        head,
        acc,
        ignore_unqualified_functions,
        lib_funs,
        allowed_packages
      )
    }

    if (length(x) >= 2L) {
      for (i in 2L:length(x)) {
        .ast_walk(
          x[[i]],
          acc,
          ignore_unqualified_functions,
          lib_funs,
          allowed_packages
        )
      }
    }

    return(invisible(NULL))
  } else if (is.expression(x)) {
    for (i in seq_along(x)) {
      .ast_walk(
        x[[i]],
        acc,
        ignore_unqualified_functions,
        lib_funs,
        allowed_packages
      )
    }
    return(invisible(NULL))
  } else if (is.pairlist(x) || is.list(x)) {
    for (i in seq_along(x)) {
      .ast_walk(
        x[[i]],
        acc,
        ignore_unqualified_functions,
        lib_funs,
        allowed_packages
      )
    }
    return(invisible(NULL))
  }

  invisible(NULL)
}

.ast_lit_name <- function(x) {
  if (is.symbol(x)) {
    return(as.character(x))
  }
  if (is.character(x) && length(x) == 1L) {
    return(x)
  }
  NULL
}

.ast_get_lib_pkg <- function(call) {
  args <- as.list(call)[-1L]
  if (!length(args)) {
    return(NULL)
  }

  nms <- names(args)
  arg <- if (!is.null(nms) && "package" %in% nms) {
    args[[match("package", nms)]]
  } else if (!is.null(nms) && "pkg" %in% nms) {
    args[[match("pkg", nms)]]
  } else {
    args[[1L]]
  }

  .ast_lit_name(arg)
}

.ast_collect_use_funs <- function(x) {
  if (is.null(x)) {
    return(character())
  }
  lit <- .ast_lit_name(x)
  if (!is.null(lit)) {
    return(lit)
  }
  if (is.call(x)) {
    head <- x[[1L]]
    head_name <- if (is.symbol(head)) as.character(head) else NULL
    if (!is.null(head_name) && head_name %in% c("c", "list")) {
      funs <- character()
      if (length(x) >= 2L) {
        for (i in 2L:length(x)) {
          funs <- c(funs, .ast_collect_use_funs(x[[i]]))
        }
      }
      return(funs)
    }
  }
  character()
}

.ast_get_use_funs <- function(call) {
  args <- as.list(call)[-1L]
  if (length(args) <= 1L) {
    return(character())
  }

  nms <- names(args)
  pkg_idx <- if (!is.null(nms) && "pkg" %in% nms) {
    match("pkg", nms)
  } else if (!is.null(nms) && "package" %in% nms) {
    match("package", nms)
  } else {
    1L
  }

  fun_args <- args[-pkg_idx]
  funs <- unlist(lapply(fun_args, .ast_collect_use_funs), use.names = FALSE)
  funs[nzchar(funs)]
}

.resolve_candidates <- function(
  unqual,
  lib_data,
  strict,
  allowed_packages = .stan_pkgs,
  export_index = .stan_export_index,
  origin_map = .stan_origin_map
) {
  allowed_packages <- unique(allowed_packages)
  if (!length(allowed_packages)) {
    return(list(
      pkgs = character(),
      keys = character(),
      ambiguous = character()
    ))
  }

  if (!length(unqual$funs)) {
    return(list(
      pkgs = character(),
      keys = character(),
      ambiguous = character()
    ))
  }

  candidates_list <- export_index[unqual$funs]
  candidates_list <- lapply(
    candidates_list,
    function(x) if (is.null(x)) NULL else x[x %in% allowed_packages]
  )
  has_candidates <- lengths(candidates_list) > 0

  if (!any(has_candidates)) {
    return(list(
      pkgs = character(),
      keys = character(),
      ambiguous = character()
    ))
  }

  idx <- unqual$idx[has_candidates]
  funs <- unqual$funs[has_candidates]
  candidates_list <- candidates_list[has_candidates]

  is_ambiguous <- lengths(candidates_list) > 1

  pkgs <- character()
  keys <- character()
  ambiguous <- character()

  # Unambiguous calls
  if (!all(is_ambiguous)) {
    best_pkgs0 <- unlist(candidates_list[!is_ambiguous], use.names = FALSE)
    funs0 <- funs[!is_ambiguous]
    keys0 <- paste0(best_pkgs0, "::", funs0)

    origin0 <- unname(origin_map[keys0])
    origin0[is.na(origin0)] <- best_pkgs0

    keep <- origin0 %in% allowed_packages
    if (any(keep)) {
      pkgs <- c(pkgs, origin0[keep])
      keys <- c(keys, paste0(origin0[keep], "::", funs0[keep]))
    }
  }

  # Ambiguous calls
  if (any(is_ambiguous)) {
    ambig_idx <- idx[is_ambiguous]
    ambig_funs <- funs[is_ambiguous]
    ambig_cands <- candidates_list[is_ambiguous]
    ambiguous <- sort(unique(ambig_funs))

    if (!strict) {
      attaching_pkgs <- character(0)
      lib_pos <- integer(0)
      if (!is.null(lib_data) && any(lib_data$is_attach)) {
        attaching_pkgs <- lib_data$pkg[lib_data$is_attach]
        lib_pos <- lib_data$pos[lib_data$is_attach]
      }

      intervals <- findInterval(ambig_idx, lib_pos)

      for (i in seq_along(ambig_idx)) {
        k <- intervals[i]
        cands <- ambig_cands[[i]]

        if (k == 0) {
          pkg <- cands[1]
        } else {
          attached_before <- attaching_pkgs[seq_len(k)]
          matches <- match(cands, attached_before)
          if (all(is.na(matches))) {
            pkg <- cands[1]
          } else {
            pkg <- cands[which.max(ifelse(is.na(matches), -1L, matches))]
          }
        }
        pkgs <- c(pkgs, pkg)
        keys <- c(keys, paste0(pkg, "::", ambig_funs[i]))
      }
    }
  }

  list(pkgs = pkgs, keys = keys, ambiguous = ambiguous)
}

#' Standard-library function names to never attribute to Stan packages
#'
#' This includes exports from: base, stats, utils, graphics, grDevices, methods.
#'
#' @return Character vector of standard-library function names.
#' @export
stdlib_funs <- function() {
  # lapply(
  #   c("base", "stats", "utils", "graphics", "grDevices", "methods"),
  #   getNamespaceExports
  # ) |>
  #   unlist(use.names = FALSE) |>
  #   unique() |>
  #   sort()
  .stdlib_funs
}
