#' Find used functions and packages
#'
#' This function is primarily exported for developers, and
#' is almost entirely divested from `stanflow`, except for
#' defaults and `{stanflow}` behavior explained later.
#'
#' The scanning is wholly static (AST parsing), so there are
#' a number of restrictions on what calls are recognized:
#' calls to `library()`, `require()`, `requireNamespace()`,
#' or `use()` are all recognized as attaching a package.
#'
#' The Stan values for `allowed_packages`, `export_index`, and `origin_map`
#' are generated by `data_raw/sysdata.R`.
#'
#' Unqualified function calls are only attributed when a Stan package is
#' attached via `library()` or `require()` in the same file. Attaching
#' `{stanflow}` is hardcoded as attaching its core packages (`bayesplot`, `loo`,
#' `posterior`, `projpred`, `shinystan`). When multiple attached Stan packages
#' export the same unqualified function, attachment order is respected: the
#' most recently attached matching package whose attachment appears before the
#' call is treated as the winner. Known reexports are remapped to their origin
#' packages; missing mappings fall back to the resolved package.
#'
#' @inheritParams stan_cite
#' @param allowed_packages Character vector of package namespaces to attribute
#'   to Stan usage. Defaults to `.stan_pkgs`.
#' @param export_index Named list mapping function names to packages. Defaults
#'   to `.stan_export_index`.
#' @param origin_map Named character vector mapping `pkg::fun` keys to the
#'   origin package. Defaults to `.stan_origin_map`.
#' @param skip_dirs Character vector of directory names to skip when scanning a
#'   directory. Defaults to `.scan_skip_dirs`.
#' @return A list of packages, resolved functions, and ambiguous function calls.
#' @export
#' @examples
#' path <- tempfile(fileext = ".R")
#' writeLines(
#'   c(
#'     "# one messy analysis file",
#'     "library(posterior)",
#'     "requireNamespace(\"brms\")",
#'     "use(\"cmdstanr\", c(\"cmdstan_model\", \"write_stan_json\"))",
#'     "draws <- as_draws(list(mu = rnorm(10)))",
#'     "posterior::rhat(draws)",
#'     "brms::mixture(0.4)",
#'     "cmdstanr::write_stan_json(list(N = 3), \"data.json\")"
#'   ),
#'   path
#' )
#' scan_usage(path, quiet = TRUE)
#' unlink(path)
scan_usage <- function(
  path = ".",
  ignore_unqualified_functions = .stdlib_funs,
  strict = FALSE,
  skip_dirs = .scan_skip_dirs,
  allowed_packages = .stan_pkgs,
  export_index = .stan_export_index,
  origin_map = .stan_origin_map,
  quiet = getOption("stanflow.quiet", FALSE)
) {
  local_cli_quiet(quiet)

  paths <- normalizePath(path, winslash = "/", mustWork = TRUE)
  dir_flags <- dir.exists(paths)

  files <- if (length(paths) == 1L && dir_flags) {
    dir_path <- paths[[1L]]
    cli::cli_alert_info("Searching directory {.path {dir_path}}")
    .scan_dir_files(dir_path, skip_dirs)
  } else {
    if (any(dir_flags)) {
      cli::cli_abort(c(
        "{.arg path} must be a single directory or a vector of files.",
        "x" = "Mixed directories and files or multiple directories are not supported."
      ))
    }
    paths |>
      (\(paths) {
        lapply(
          paths,
          \(file_path) cli::cli_alert_info("Searching {.path {file_path}}")
        )
        paths
      })()
  }

  if (!length(files)) {
    cli::cli_abort(c(
      "No files found.",
      "i" = "Check the {.arg path} and {.arg skip_dirs} arguments."
    ))
  }

  hits <- unique(files) |>
    lapply(
      \(file) {
        file |>
          .extract_code() |>
          .scan_tokens(
            ignore_unqualified_functions = ignore_unqualified_functions,
            allowed_packages = allowed_packages,
            export_index = export_index,
            origin_map = origin_map,
            file_path = file
          )
      }
    )

  ambiguous <- .collect_unique(hits, "ambiguous")
  if (length(ambiguous)) {
    msg <- c(
      "Cannot reliably detect which packages some functions are from.",
      "x" = paste0(
        "Ambiguous functions: ",
        paste0("{.fun ", ambiguous, "}", collapse = ", ")
      ),
      "i" = "Please namespace them ({.code pkg::function()}) and rerun or set {.code strict = FALSE}."
    )

    if (strict) cli::cli_abort(msg) else cli::cli_warn(msg)
  }

  structure(
    list(
      packages = .collect_unique(hits, "pkgs"),
      functions = .collect_unique(hits, "keys"),
      ambiguous = ambiguous
    ),
    class = "scan_usage"
  )
}

.scan_skip_regex <- function(skip_dirs) {
  escaped <- vapply(
    skip_dirs,
    \(x) gsub("([][{}()+*^$|\\\\.?])", "\\\\\\1", x),
    character(1)
  )
  paste0("(^|/)(?:", paste(escaped, collapse = "|"), ")(/|$)")
}

.scan_dir_walk <- function(path, skip_dirs, file_cb) {
  entries <- list.files(
    path,
    all.files = TRUE,
    full.names = TRUE,
    no.. = TRUE
  )
  if (!length(entries)) {
    return(invisible(NULL))
  }

  is_dir <- dir.exists(entries)

  if (any(is_dir)) {
    dirs <- entries[is_dir]
    if (length(skip_dirs)) {
      keep <- is.na(fastmatch::fmatch(basename(dirs), skip_dirs))
      dirs <- dirs[keep]
    }
    if (length(dirs)) {
      for (dir in dirs) {
        .scan_dir_walk(dir, skip_dirs, file_cb)
      }
    }
  }

  if (!all(is_dir)) {
    file_cb(entries[!is_dir])
  }

  invisible(NULL)
}

.scan_dir_files <- function(dir_path, skip_dirs) {
  dir_path <- normalizePath(dir_path, winslash = "/", mustWork = TRUE)
  files <- character()
  n <- 0L

  add_code_files <- function(paths) {
    code_files <- paths[grepl("\\.(R|Rmd|Qmd)$", paths, ignore.case = TRUE)]
    if (!length(code_files)) {
      return(invisible(NULL))
    }

    idx <- seq.int(n + 1L, n + length(code_files))
    files[idx] <<- code_files
    n <<- idx[length(idx)]

    invisible(NULL)
  }

  .scan_dir_walk(dir_path, skip_dirs, add_code_files)
  normalizePath(files, winslash = "/", mustWork = FALSE)
}

.collect_unique <- function(hits, field) {
  hits |>
    lapply(`[[`, field) |>
    unlist(use.names = FALSE) |>
    unique() |>
    sort()
}

.extract_code <- function(file) {
  ext <- file |>
    sub(".*\\.", "", x = _) |>
    tolower()

  if (!ext %in% c("r", "rmd", "qmd")) {
    cli::cli_abort(c(
      "Unsupported file extension: {.val {ext}}.",
      "i" = "Supported extensions are {.file .R}, {.file .Rmd}, and {.file .qmd}."
    ))
  }

  if (ext == "r") {
    return(paste(readLines(file, warn = FALSE), collapse = "\n"))
  }
  if (!requireNamespace("knitr", quietly = TRUE)) {
    cli::cli_abort(c(
      "Package {.pkg knitr} is required to parse R Markdown ({.file .Rmd}) or Quarto ({.file .qmd}) files.",
      "i" = "Please install it with {.code install.packages('knitr')}."
    ))
  }

  tmp <- withr::local_tempfile(fileext = ".R")
  knitr::purl(file, tmp, quiet = TRUE, documentation = 0)

  paste(readLines(tmp, warn = FALSE), collapse = "\n")
}

.scan_tokens <- function(
  code,
  ignore_unqualified_functions,
  allowed_packages = .stan_pkgs,
  export_index = .stan_export_index,
  origin_map = .stan_origin_map,
  file_path = NULL
) {
  empty <- list(pkgs = character(), keys = character(), ambiguous = character())
  expr <- tryCatch(
    parse(text = code, keep.source = FALSE),
    error = function(e) NULL
  )
  if (is.null(expr)) {
    path_label <- if (!is.null(file_path) && nzchar(file_path)) {
      file_path
    } else {
      "<unknown file>"
    }
    msg <- c(
      "Failed to parse {.path {path_label}}.",
      "x" = "Syntax error in file."
    )
    cli::cli_warn(msg)
    return(empty)
  }

  acc <- new.env(parent = emptyenv())
  acc$visit_idx <- 0L
  acc$lib_pkgs <- character()
  acc$lib_visit_idx <- integer()
  acc$lib_is_attach <- logical()
  acc$ns_pkgs <- character()
  acc$ns_keys <- character()
  acc$unqual_funs <- character()
  acc$unqual_visit_idx <- integer()

  lib_funs <- c("library", "require", "requireNamespace")
  ns_ops <- c("::", ":::")
  use_heads <- c("c", "list")
  ignore_heads <- c(
    "if",
    "for",
    "while",
    "repeat",
    "function",
    "return",
    "next",
    "break",
    "{",
    "(",
    "<-",
    "<<-",
    "->",
    "->>",
    "=",
    "+",
    "-",
    "*",
    "/",
    "^",
    "%%",
    "%/%",
    "%*%",
    "%>%",
    ":",
    "|",
    "&",
    "||",
    "&&",
    "!",
    "~",
    "|>",
    "$",
    "@",
    "[",
    "[["
  )
  export_names <- names(export_index)
  if (is.null(export_names)) {
    export_names <- character()
  }

  for (i in seq_along(expr)) {
    .ast_walk(
      expr[[i]],
      acc,
      ignore_unqualified_functions,
      lib_funs,
      allowed_packages,
      ns_ops,
      use_heads,
      ignore_heads,
      export_names
    )
  }

  lib_data <- if (length(acc$lib_pkgs)) {
    data.frame(
      visit_idx = acc$lib_visit_idx,
      pkg = acc$lib_pkgs,
      is_attach = acc$lib_is_attach,
      stringsAsFactors = FALSE
    )
  } else {
    NULL
  }

  resolved <- .resolve_candidates(
    list(funs = acc$unqual_funs, idx = acc$unqual_visit_idx),
    lib_data,
    allowed_packages,
    export_index,
    origin_map
  )

  list(
    pkgs = c(acc$lib_pkgs, acc$ns_pkgs, resolved$pkgs),
    keys = c(acc$ns_keys, resolved$keys),
    ambiguous = resolved$ambiguous
  )
}

.ast_walk <- function(
  x,
  acc,
  ignore_unqualified_functions,
  lib_funs,
  allowed_packages,
  ns_ops,
  use_heads,
  ignore_heads,
  export_names
) {
  if (is.null(x)) {
    return(invisible(NULL))
  }

  if (is.call(x)) {
    acc$visit_idx <- acc$visit_idx + 1L

    head <- x[[1L]]
    head_name <- if (is.symbol(head)) as.character(head) else NULL
    member_fun <- .ast_member_fun(head)

    # Member calls (e.g., obj$sample()) are package API methods, not
    # language-level calls; don't suppress them via stdlib ignore lists.
    if (
      !is.null(member_fun) &&
        !is.na(fastmatch::fmatch(member_fun, export_names))
    ) {
      acc$unqual_funs <- c(acc$unqual_funs, member_fun)
      acc$unqual_visit_idx <- c(acc$unqual_visit_idx, acc$visit_idx)
    }

    if (!is.null(head_name)) {
      if (!is.na(fastmatch::fmatch(head_name, ns_ops)) && length(x) >= 3L) {
        pkg <- .ast_lit_name(x[[2L]])
        fun <- .ast_lit_name(x[[3L]])
        if (
          !is.null(pkg) &&
            !is.null(fun) &&
            !is.na(fastmatch::fmatch(pkg, allowed_packages))
        ) {
          acc$ns_pkgs <- c(acc$ns_pkgs, pkg)
          acc$ns_keys <- c(acc$ns_keys, paste0(pkg, "::", fun))
        }
      } else if (head_name == "use") {
        pkg <- .ast_get_lib_pkg(x)
        if (!is.null(pkg) && !is.na(fastmatch::fmatch(pkg, allowed_packages))) {
          acc$ns_pkgs <- c(acc$ns_pkgs, pkg)
          funs <- .ast_get_use_funs(x, use_heads)
          if (length(funs)) {
            acc$ns_keys <- c(acc$ns_keys, paste0(pkg, "::", funs))
          }
        }
      } else if (!is.na(fastmatch::fmatch(head_name, lib_funs))) {
        pkg <- .ast_get_lib_pkg(x)
        if (!is.null(pkg)) {
          is_allowed <- !is.na(fastmatch::fmatch(pkg, allowed_packages))
          is_attach <- head_name != "requireNamespace"

          if (is_allowed) {
            acc$lib_pkgs <- c(acc$lib_pkgs, pkg)
            acc$lib_visit_idx <- c(acc$lib_visit_idx, acc$visit_idx)
            acc$lib_is_attach <- c(acc$lib_is_attach, is_attach)
          }

          if (pkg == "stanflow" && is_attach) {
            core_pkgs <- core
            if (length(core_pkgs)) {
              core_pkgs <- core_pkgs[
                !is.na(fastmatch::fmatch(core_pkgs, allowed_packages))
              ]
            }
            if (length(core_pkgs)) {
              acc$lib_pkgs <- c(acc$lib_pkgs, core_pkgs)
              acc$lib_visit_idx <- c(
                acc$lib_visit_idx,
                rep.int(acc$visit_idx, length(core_pkgs))
              )
              acc$lib_is_attach <- c(
                acc$lib_is_attach,
                rep.int(TRUE, length(core_pkgs))
              )
            }
          }
        }
      } else if (!is.na(fastmatch::fmatch(head_name, ignore_heads))) {
        # Skip language keywords, operators, and subsetting.
      } else if (is.na(fastmatch::fmatch(head_name, export_names))) {
        # Ignore non-Stan calls before consulting broader ignore lists.
      } else if (
        is.na(fastmatch::fmatch(head_name, ignore_unqualified_functions))
      ) {
        acc$unqual_funs <- c(acc$unqual_funs, head_name)
        acc$unqual_visit_idx <- c(acc$unqual_visit_idx, acc$visit_idx)
      }
    }

    if (is.call(head)) {
      .ast_walk(
        head,
        acc,
        ignore_unqualified_functions,
        lib_funs,
        allowed_packages,
        ns_ops,
        use_heads,
        ignore_heads,
        export_names
      )
    }
    n <- length(x)
    if (n >= 2L) {
      for (i in 2L:n) {
        .ast_walk(
          x[[i]],
          acc,
          ignore_unqualified_functions,
          lib_funs,
          allowed_packages,
          ns_ops,
          use_heads,
          ignore_heads,
          export_names
        )
      }
    }
    return(invisible(NULL))
  }

  if (is.expression(x) || is.pairlist(x) || is.list(x)) {
    for (i in seq_along(x)) {
      .ast_walk(
        x[[i]],
        acc,
        ignore_unqualified_functions,
        lib_funs,
        allowed_packages,
        ns_ops,
        use_heads,
        ignore_heads,
        export_names
      )
    }
    return(invisible(NULL))
  }

  invisible(NULL)
}

.ast_lit_name <- function(x) {
  if (is.symbol(x)) {
    return(as.character(x))
  }
  if (is.character(x) && length(x) == 1L) {
    return(x)
  }
  NULL
}

.ast_member_fun <- function(head) {
  if (!is.call(head) || !length(head)) {
    return(NULL)
  }

  op <- head[[1L]]
  if (!is.symbol(op)) {
    return(NULL)
  }

  op_name <- as.character(op)

  if (op_name %in% c("$", "@") && length(head) >= 3L) {
    return(.ast_lit_name(head[[3L]]))
  }

  if (op_name == "(" && length(head) >= 2L) {
    return(.ast_member_fun(head[[2L]]))
  }

  NULL
}

.ast_get_lib_pkg <- function(call) {
  n <- length(call)
  if (n <= 1L) {
    return(NULL)
  }

  nms <- names(call)
  arg_nms <- if (!is.null(nms) && n >= 2L) nms[-1L] else NULL
  pkg_i <- if (!is.null(arg_nms)) {
    fastmatch::fmatch("package", arg_nms)
  } else {
    NA_integer_
  }
  pkg_j <- if (!is.null(arg_nms)) {
    fastmatch::fmatch("pkg", arg_nms)
  } else {
    NA_integer_
  }

  arg_idx <- if (!is.na(pkg_i)) {
    pkg_i + 1L
  } else if (!is.na(pkg_j)) {
    pkg_j + 1L
  } else {
    2L
  }

  .ast_lit_name(call[[arg_idx]])
}

.ast_collect_use_funs <- function(x, use_heads) {
  if (is.null(x)) {
    return(character())
  }

  lit <- .ast_lit_name(x)
  if (!is.null(lit)) {
    return(lit)
  }

  if (is.call(x)) {
    head <- x[[1L]]
    head_name <- if (is.symbol(head)) as.character(head) else NULL
    if (
      !is.null(head_name) && !is.na(fastmatch::fmatch(head_name, use_heads))
    ) {
      n <- length(x)
      if (n <= 1L) {
        return(character())
      }
      out <- vector("list", n - 1L)
      for (i in 2L:n) {
        out[[i - 1L]] <- .ast_collect_use_funs(x[[i]], use_heads = use_heads)
      }
      return(unlist(out, use.names = FALSE))
    }
  }

  character()
}

.ast_get_use_funs <- function(call, use_heads) {
  n <- length(call)
  if (n <= 2L) {
    return(character())
  }

  nms <- names(call)
  arg_nms <- if (!is.null(nms)) nms[-1L] else NULL
  pkg_i <- if (!is.null(arg_nms)) {
    fastmatch::fmatch("pkg", arg_nms)
  } else {
    NA_integer_
  }
  pkg_j <- if (!is.null(arg_nms)) {
    fastmatch::fmatch("package", arg_nms)
  } else {
    NA_integer_
  }

  pkg_idx <- if (!is.na(pkg_i)) {
    pkg_i
  } else if (!is.na(pkg_j)) {
    pkg_j
  } else {
    1L
  }

  out <- vector("list", n - 2L)
  j <- 0L
  for (i in 2L:n) {
    arg_idx <- i - 1L
    if (arg_idx == pkg_idx) {
      next
    }
    j <- j + 1L
    out[[j]] <- .ast_collect_use_funs(call[[i]], use_heads = use_heads)
  }
  funs <- unlist(out, use.names = FALSE)
  funs[nzchar(funs)]
}

.origin_pkg <- function(
  pkg,
  fun,
  origin_map = .stan_origin_map
) {
  origin <- unname(origin_map[paste0(pkg, "::", fun)])
  if (is.na(origin)) pkg else origin
}

.resolve_origin_pkg <- function(
  pkg,
  fun,
  origin_map = .stan_origin_map,
  allowed_packages = .stan_pkgs
) {
  origin <- .origin_pkg(pkg, fun, origin_map)
  if (is.na(fastmatch::fmatch(origin, allowed_packages))) pkg else origin
}

.resolve_candidates <- function(
  unqual,
  lib_data,
  allowed_packages = .stan_pkgs,
  export_index = .stan_export_index,
  origin_map = .stan_origin_map
) {
  empty <- list(pkgs = character(), keys = character(), ambiguous = character())
  if (!length(unqual$funs) || !length(allowed_packages)) {
    return(empty)
  }

  attached_pkgs <- character()
  attached_visit_idx <- integer()
  if (!is.null(lib_data) && any(lib_data$is_attach)) {
    attached_pkgs <- lib_data$pkg[lib_data$is_attach]
    attached_visit_idx <- lib_data$visit_idx[lib_data$is_attach]
  }
  if (!length(attached_pkgs)) {
    return(empty)
  }

  if (length(attached_visit_idx) > 1L) {
    ord <- order(attached_visit_idx, seq_along(attached_visit_idx))
    attached_pkgs <- attached_pkgs[ord]
    attached_visit_idx <- attached_visit_idx[ord]
  }

  unique_funs <- unique(unqual$funs)
  meta_by_fun <- setNames(
    lapply(unique_funs, function(fun) {
      providers <- export_index[[fun]]
      if (is.null(providers) || !length(providers)) {
        return(NULL)
      }

      providers <- providers[
        !is.na(fastmatch::fmatch(providers, allowed_packages)) &
          !is.na(fastmatch::fmatch(providers, attached_pkgs))
      ]
      if (!length(providers)) {
        return(NULL)
      }

      origins <- vapply(
        providers,
        .origin_pkg,
        character(1),
        fun = fun,
        origin_map = origin_map
      )
      origins <- origins[!is.na(fastmatch::fmatch(origins, allowed_packages))]
      if (!length(origins)) {
        return(NULL)
      }

      list(
        providers = providers,
        unique_origins = unique(origins)
      )
    }),
    unique_funs
  )

  has_meta <- !vapply(meta_by_fun[unqual$funs], is.null, logical(1))
  if (!any(has_meta)) {
    return(empty)
  }

  idx <- unqual$idx[has_meta]
  funs <- unqual$funs[has_meta]
  if (length(idx) > 1L) {
    ord <- order(idx, seq_along(idx))
    idx <- idx[ord]
    funs <- funs[ord]
  }

  intervals <- findInterval(idx, attached_visit_idx)
  resolved_pkgs <- character(length(idx))
  resolved <- logical(length(idx))

  for (i in seq_along(idx)) {
    meta <- meta_by_fun[[funs[[i]]]]
    if (length(meta$unique_origins) == 1L) {
      resolved_pkgs[[i]] <- meta$unique_origins[[1L]]
      resolved[[i]] <- TRUE
      next
    }

    k <- intervals[[i]]
    if (k == 0L) {
      next
    }

    attached_before <- attached_pkgs[seq_len(k)]
    matches <- fastmatch::fmatch(meta$providers, attached_before)
    if (all(is.na(matches))) {
      next
    }

    pkg <- meta$providers[[which.max(ifelse(is.na(matches), -1L, matches))]]
    resolved_pkgs[[i]] <- .resolve_origin_pkg(
      pkg,
      funs[[i]],
      origin_map,
      allowed_packages
    )
    resolved[[i]] <- TRUE
  }

  list(
    pkgs = resolved_pkgs[resolved],
    keys = if (any(resolved)) {
      paste0(resolved_pkgs[resolved], "::", funs[resolved])
    } else {
      character()
    },
    ambiguous = if (all(resolved)) {
      character()
    } else {
      sort(unique(funs[!resolved]))
    }
  )
}

#' Ignored functions/directories used by scanner
#'
#' @name internal_data
#' @rdname internal_data
#' @keywords internal
NULL

#' Default ignored functions
#'
#' Vector of functions to be ignored when parsing.
#' Generated in `data-raw/sysdata.R` from exports of base R packages.
#'
#' @rdname internal_data
#' @export
#' @examples
#' head(stdlib_funs())
stdlib_funs <- function() {
  # lapply(
  #   c("base", "stats", "utils", "graphics", "grDevices", "methods"),
  #   getNamespaceExports
  # ) |>
  #   unlist(use.names = FALSE) |>
  #   unique() |>
  #   sort()
  .stdlib_funs
}

#' Default skip directories
#'
#' Vector of directories skipped when recursively searching
#' a project. Generated in `data-raw/sysdata.R`.
#'
#' @rdname internal_data
#' @export
#' @examples
#' scan_skip_dirs()
scan_skip_dirs <- function() {
  # c(
  #   "renv",
  #   "packrat",
  #   "rv",
  #   ".Rcheck",
  #   "revdep",
  #   "_site",
  #   "_book",
  #   "_bookdown_files",
  #   "_freeze",
  #   ".quarto",
  #   ".quarto_cache",
  #   ".knitr_cache",
  #   "_cache",
  #   ".cache"
  # )
  .scan_skip_dirs
}
