#' Find used functions and packages
#'
#' This function is primarily exported for developers, and
#' is almost entirely divested from `stanflow`, except for
#' defaults and `{stanflow}` behavior explained later.
#'
#' The scanning is wholly static (AST parsing), so there are
#' a number of restrictions on what calls are recognized:
#' calls to `library()`, `require()`, `requireNamespace()`,
#' or `use()` are all recognized as attaching a package.
#'
#' The Stan values for `allowed_packages`, `export_index`, and `origin_map`
#' are generated by `data_raw/sysdata.R`.
#'
#' Unqualified function calls are only attributed when a Stan package is
#' attached via `library()` or `require()` in the same file. Attaching
#' `{stanflow}` is hardcoded as attaching its core packages (`bayesplot`, `loo`,
#' `posterior`, `projpred`, `shinystan`). When multiple attached Stan packages
#' export the same unqualified function, attachment order is respected: the
#' most recently attached matching package whose attachment appears before the
#' call is treated as the winner. Known reexports are remapped to their origin
#' packages; missing mappings fall back to the resolved package.
#'
#' @inheritParams stan_cite
#' @param allowed_packages Character vector of package namespaces to attribute
#'   to Stan usage. Defaults to `.stan_pkgs`.
#' @param export_index Named list mapping function names to packages. Defaults
#'   to `.stan_export_index`.
#' @param origin_map Named character vector mapping `pkg::fun` keys to the
#'   origin package. Defaults to `.stan_origin_map`.
#' @param skip_dirs Character vector of directory names to skip when scanning a
#'   directory. Defaults to `.scan_skip_dirs`.
#' @return A list of packages, resolved functions, and ambiguous function calls.
#' @export
#' @examples
#' path <- tempfile(fileext = ".R")
#' writeLines(
#'   c(
#'     "# one messy analysis file",
#'     "library(posterior)",
#'     "requireNamespace(\"brms\")",
#'     "use(\"cmdstanr\", c(\"cmdstan_model\", \"write_stan_json\"))",
#'     "draws <- as_draws(list(mu = rnorm(10)))",
#'     "posterior::rhat(draws)",
#'     "brms::mixture(0.4)",
#'     "cmdstanr::write_stan_json(list(N = 3), \"data.json\")"
#'   ),
#'   path
#' )
#' scan_usage(path, quiet = TRUE)
#' unlink(path)
scan_usage <- function(
  path = ".",
  ignore_unqualified_functions = .stdlib_funs,
  strict = FALSE,
  skip_dirs = .scan_skip_dirs,
  allowed_packages = .stan_pkgs,
  export_index = .stan_export_index,
  origin_map = .stan_origin_map,
  quiet = getOption("stanflow.quiet", FALSE)
) {
  local_cli_quiet(quiet)

  paths <- normalizePath(path, winslash = "/", mustWork = TRUE)
  dir_flags <- dir.exists(paths)

  files <- if (length(paths) == 1L && dir_flags) {
    dir_path <- paths[[1L]]
    cli::cli_alert_info("Searching directory {.path {dir_path}}")
    .scan_dir_files(dir_path, skip_dirs)
  } else {
    if (any(dir_flags)) {
      cli::cli_abort(c(
        "{.arg path} must be a single directory or a vector of files.",
        "x" = "Mixed directories and files or multiple directories are not supported."
      ))
    }
    paths |>
      (\(paths) {
        lapply(
          paths,
          \(file_path) cli::cli_alert_info("Searching {.path {file_path}}")
        )
        paths
      })()
  }

  if (!length(files)) {
    cli::cli_abort(c(
      "No files found.",
      "i" = "Check the {.arg path} and {.arg skip_dirs} arguments."
    ))
  }

  hits <- unique(files) |>
    lapply(
      \(file) {
        file |>
          .extract_code() |>
          .scan_tokens(
            ignore_unqualified_functions = ignore_unqualified_functions,
            allowed_packages = allowed_packages,
            export_index = export_index,
            origin_map = origin_map,
            file_path = file
          )
      }
    )

  ambiguous <- .collect_unique(hits, "ambiguous")
  if (length(ambiguous)) {
    msg <- c(
      "Cannot reliably detect which packages some functions are from.",
      "x" = paste0(
        "Ambiguous functions: ",
        paste0("{.fun ", ambiguous, "}", collapse = ", ")
      ),
      "i" = "Please namespace them ({.code pkg::function()}) and rerun or set {.code strict = FALSE}."
    )

    if (strict) cli::cli_abort(msg) else cli::cli_warn(msg)
  }

  structure(
    list(
      packages = .collect_unique(hits, "pkgs"),
      functions = .collect_unique(hits, "keys"),
      ambiguous = ambiguous
    ),
    class = "scan_usage"
  )
}

.scan_skip_regex <- function(skip_dirs) {
  escaped <- vapply(
    skip_dirs,
    \(x) gsub("([][{}()+*^$|\\\\.?])", "\\\\\\1", x),
    character(1)
  )
  paste0("(^|/)(?:", paste(escaped, collapse = "|"), ")(/|$)")
}

.scan_dir_files <- function(dir_path, skip_dirs) {
  dir_path <- normalizePath(dir_path, winslash = "/", mustWork = TRUE)
  files <- list.files(
    dir_path,
    recursive = TRUE,
    pattern = "\\.(R|Rmd|Qmd)$",
    ignore.case = TRUE,
    all.files = TRUE,
    full.names = TRUE,
    no.. = TRUE
  )
  files <- normalizePath(
    files[!dir.exists(files)],
    winslash = "/",
    mustWork = FALSE
  )

  if (length(skip_dirs) && length(files)) {
    rel_files <- sub(paste0("^", dir_path, "/?"), "", files)
    files <- files[!grepl(.scan_skip_regex(skip_dirs), rel_files)]
  }

  files
}

.collect_unique <- function(hits, field) {
  hits |>
    lapply(`[[`, field) |>
    unlist(use.names = FALSE) |>
    unique() |>
    sort()
}

.extract_code <- function(file) {
  ext <- file |>
    sub(".*\\.", "", x = _) |>
    tolower()

  if (!ext %in% c("r", "rmd", "qmd")) {
    cli::cli_abort(c(
      "Unsupported file extension: {.val {ext}}.",
      "i" = "Supported extensions are {.file .R}, {.file .Rmd}, and {.file .qmd}."
    ))
  }

  if (ext == "r") {
    return(paste(readLines(file, warn = FALSE), collapse = "\n"))
  }
  if (!requireNamespace("knitr", quietly = TRUE)) {
    cli::cli_abort(c(
      "Package {.pkg knitr} is required to parse R Markdown ({.file .Rmd}) or Quarto ({.file .qmd}) files.",
      "i" = "Please install it with {.code install.packages('knitr')}."
    ))
  }

  tmp <- withr::local_tempfile(fileext = ".R")
  knitr::purl(file, tmp, quiet = TRUE, documentation = 0)

  paste(readLines(tmp, warn = FALSE), collapse = "\n")
}

.scan_tokens <- function(
  code,
  ignore_unqualified_functions,
  allowed_packages = .stan_pkgs,
  export_index = .stan_export_index,
  origin_map = .stan_origin_map,
  file_path = NULL
) {
  empty <- list(pkgs = character(), keys = character(), ambiguous = character())
  expr <- tryCatch(
    parse(text = code, keep.source = FALSE),
    error = function(e) NULL
  )
  if (is.null(expr)) {
    path_label <- if (!is.null(file_path) && nzchar(file_path)) {
      file_path
    } else {
      "<unknown file>"
    }
    msg <- c(
      "Failed to parse {.path {path_label}}.",
      "x" = "Syntax error in file."
    )
    cli::cli_warn(msg)
    return(empty)
  }

  acc <- new.env(parent = emptyenv())
  acc$visit_idx <- 0L
  acc$lib_pkgs <- character()
  acc$lib_visit_idx <- integer()
  acc$lib_is_attach <- logical()
  acc$ns_pkgs <- character()
  acc$ns_keys <- character()
  acc$unqual_funs <- character()
  acc$unqual_visit_idx <- integer()

  lib_funs <- c("library", "require", "requireNamespace")
  ns_ops <- c("::", ":::")
  use_heads <- c("c", "list")
  ignore_heads <- c(
    "if",
    "for",
    "while",
    "repeat",
    "function",
    "return",
    "next",
    "break",
    "{",
    "(",
    "<-",
    "<<-",
    "->",
    "->>",
    "=",
    "+",
    "-",
    "*",
    "/",
    "^",
    "%%",
    "%/%",
    "%*%",
    "%>%",
    ":",
    "|",
    "&",
    "||",
    "&&",
    "!",
    "~",
    "|>",
    "$",
    "@",
    "[",
    "[["
  )

  for (i in seq_along(expr)) {
    .ast_walk(
      expr[[i]],
      acc,
      ignore_unqualified_functions,
      lib_funs,
      allowed_packages,
      ns_ops,
      use_heads,
      ignore_heads
    )
  }

  lib_data <- if (length(acc$lib_pkgs)) {
    data.frame(
      visit_idx = acc$lib_visit_idx,
      pkg = acc$lib_pkgs,
      is_attach = acc$lib_is_attach,
      stringsAsFactors = FALSE
    )
  } else {
    NULL
  }

  resolved <- .resolve_candidates(
    list(funs = acc$unqual_funs, idx = acc$unqual_visit_idx),
    lib_data,
    allowed_packages,
    export_index,
    origin_map
  )

  list(
    pkgs = c(acc$lib_pkgs, acc$ns_pkgs, resolved$pkgs),
    keys = c(acc$ns_keys, resolved$keys),
    ambiguous = resolved$ambiguous
  )
}

.ast_walk <- function(
  x,
  acc,
  ignore_unqualified_functions,
  lib_funs,
  allowed_packages,
  ns_ops,
  use_heads,
  ignore_heads
) {
  if (is.null(x)) {
    return(invisible(NULL))
  }

  if (is.call(x)) {
    acc$visit_idx <- acc$visit_idx + 1L

    head <- x[[1L]]
    head_name <- if (is.symbol(head)) as.character(head) else NULL
    member_fun <- .ast_member_fun(head)

    # Member calls (e.g., obj$sample()) are package API methods, not
    # language-level calls; don't suppress them via stdlib ignore lists.
    if (!is.null(member_fun)) {
      acc$unqual_funs <- c(acc$unqual_funs, member_fun)
      acc$unqual_visit_idx <- c(acc$unqual_visit_idx, acc$visit_idx)
    }

    if (!is.null(head_name)) {
      if (!is.na(fastmatch::fmatch(head_name, ns_ops)) && length(x) >= 3L) {
        pkg <- .ast_lit_name(x[[2L]])
        fun <- .ast_lit_name(x[[3L]])
        if (
          !is.null(pkg) &&
            !is.null(fun) &&
            !is.na(fastmatch::fmatch(pkg, allowed_packages))
        ) {
          acc$ns_pkgs <- c(acc$ns_pkgs, pkg)
          acc$ns_keys <- c(acc$ns_keys, paste0(pkg, "::", fun))
        }
      } else if (head_name == "use") {
        pkg <- .ast_get_lib_pkg(x)
        if (!is.null(pkg) && !is.na(fastmatch::fmatch(pkg, allowed_packages))) {
          acc$ns_pkgs <- c(acc$ns_pkgs, pkg)
          funs <- .ast_get_use_funs(x, use_heads)
          if (length(funs)) {
            acc$ns_keys <- c(acc$ns_keys, paste0(pkg, "::", funs))
          }
        }
      } else if (!is.na(fastmatch::fmatch(head_name, lib_funs))) {
        pkg <- .ast_get_lib_pkg(x)
        if (!is.null(pkg)) {
          is_allowed <- !is.na(fastmatch::fmatch(pkg, allowed_packages))
          is_attach <- head_name != "requireNamespace"

          if (is_allowed) {
            acc$lib_pkgs <- c(acc$lib_pkgs, pkg)
            acc$lib_visit_idx <- c(acc$lib_visit_idx, acc$visit_idx)
            acc$lib_is_attach <- c(acc$lib_is_attach, is_attach)
          }

          if (pkg == "stanflow" && is_attach) {
            core_pkgs <- core
            if (length(core_pkgs)) {
              core_pkgs <- core_pkgs[
                !is.na(fastmatch::fmatch(core_pkgs, allowed_packages))
              ]
            }
            if (length(core_pkgs)) {
              acc$lib_pkgs <- c(acc$lib_pkgs, core_pkgs)
              acc$lib_visit_idx <- c(
                acc$lib_visit_idx,
                rep.int(acc$visit_idx, length(core_pkgs))
              )
              acc$lib_is_attach <- c(
                acc$lib_is_attach,
                rep.int(TRUE, length(core_pkgs))
              )
            }
          }
        }
      } else if (!is.na(fastmatch::fmatch(head_name, ignore_heads))) {
        # Skip language keywords, operators, and subsetting.
      } else if (
        is.na(fastmatch::fmatch(head_name, ignore_unqualified_functions))
      ) {
        acc$unqual_funs <- c(acc$unqual_funs, head_name)
        acc$unqual_visit_idx <- c(acc$unqual_visit_idx, acc$visit_idx)
      }
    }

    if (is.call(head)) {
      .ast_walk(
        head,
        acc,
        ignore_unqualified_functions,
        lib_funs,
        allowed_packages,
        ns_ops,
        use_heads,
        ignore_heads
      )
    }
    children <- as.list(x)[-1L]
    if (length(children)) {
      for (i in seq_along(children)) {
        .ast_walk(
          children[[i]],
          acc,
          ignore_unqualified_functions,
          lib_funs,
          allowed_packages,
          ns_ops,
          use_heads,
          ignore_heads
        )
      }
    }
    return(invisible(NULL))
  }

  if (is.expression(x) || is.pairlist(x) || is.list(x)) {
    for (i in seq_along(x)) {
      .ast_walk(
        x[[i]],
        acc,
        ignore_unqualified_functions,
        lib_funs,
        allowed_packages,
        ns_ops,
        use_heads,
        ignore_heads
      )
    }
    return(invisible(NULL))
  }

  invisible(NULL)
}

.ast_lit_name <- function(x) {
  if (is.symbol(x)) {
    return(as.character(x))
  }
  if (is.character(x) && length(x) == 1L) {
    return(x)
  }
  NULL
}

.ast_member_fun <- function(head) {
  if (!is.call(head) || !length(head)) {
    return(NULL)
  }

  op <- head[[1L]]
  if (!is.symbol(op)) {
    return(NULL)
  }

  op_name <- as.character(op)

  if (op_name %in% c("$", "@") && length(head) >= 3L) {
    return(.ast_lit_name(head[[3L]]))
  }

  if (op_name == "(" && length(head) >= 2L) {
    return(.ast_member_fun(head[[2L]]))
  }

  NULL
}

.ast_get_lib_pkg <- function(call) {
  args <- as.list(call)[-1L]
  if (!length(args)) {
    return(NULL)
  }

  nms <- names(args)
  pkg_i <- if (!is.null(nms)) fastmatch::fmatch("package", nms) else NA_integer_
  pkg_j <- if (!is.null(nms)) fastmatch::fmatch("pkg", nms) else NA_integer_

  arg <- if (!is.na(pkg_i)) {
    args[[pkg_i]]
  } else if (!is.na(pkg_j)) {
    args[[pkg_j]]
  } else {
    args[[1L]]
  }

  .ast_lit_name(arg)
}

.ast_collect_use_funs <- function(x, use_heads) {
  if (is.null(x)) {
    return(character())
  }

  lit <- .ast_lit_name(x)
  if (!is.null(lit)) {
    return(lit)
  }

  if (is.call(x)) {
    head <- x[[1L]]
    head_name <- if (is.symbol(head)) as.character(head) else NULL
    if (
      !is.null(head_name) && !is.na(fastmatch::fmatch(head_name, use_heads))
    ) {
      args <- as.list(x)[-1L]
      if (!length(args)) {
        return(character())
      }
      return(unlist(
        lapply(args, .ast_collect_use_funs, use_heads = use_heads),
        use.names = FALSE
      ))
    }
  }

  character()
}

.ast_get_use_funs <- function(call, use_heads) {
  args <- as.list(call)[-1L]
  if (length(args) <= 1L) {
    return(character())
  }

  nms <- names(args)
  pkg_i <- if (!is.null(nms)) fastmatch::fmatch("pkg", nms) else NA_integer_
  pkg_j <- if (!is.null(nms)) fastmatch::fmatch("package", nms) else NA_integer_

  pkg_idx <- if (!is.na(pkg_i)) {
    pkg_i
  } else if (!is.na(pkg_j)) {
    pkg_j
  } else {
    1L
  }

  fun_args <- args[-pkg_idx]
  funs <- unlist(
    lapply(fun_args, .ast_collect_use_funs, use_heads = use_heads),
    use.names = FALSE
  )
  funs[nzchar(funs)]
}

.origin_pkg <- function(
  pkg,
  fun,
  origin_map = .stan_origin_map
) {
  origin <- unname(origin_map[paste0(pkg, "::", fun)])
  if (is.na(origin)) pkg else origin
}

.resolve_origin_pkg <- function(
  pkg,
  fun,
  origin_map = .stan_origin_map,
  allowed_packages = .stan_pkgs
) {
  origin <- .origin_pkg(pkg, fun, origin_map)
  if (is.na(fastmatch::fmatch(origin, allowed_packages))) pkg else origin
}

.resolve_candidates <- function(
  unqual,
  lib_data,
  allowed_packages = .stan_pkgs,
  export_index = .stan_export_index,
  origin_map = .stan_origin_map
) {
  empty <- list(pkgs = character(), keys = character(), ambiguous = character())
  if (!length(unqual$funs) || !length(allowed_packages)) {
    return(empty)
  }

  attached_pkgs <- character()
  attached_visit_idx <- integer()
  if (!is.null(lib_data) && any(lib_data$is_attach)) {
    attached_pkgs <- lib_data$pkg[lib_data$is_attach]
    attached_visit_idx <- lib_data$visit_idx[lib_data$is_attach]
  }
  if (!length(attached_pkgs)) {
    return(empty)
  }

  candidates_list <- export_index[unqual$funs] |>
    lapply(\(x) x[!is.na(fastmatch::fmatch(x, allowed_packages))])
  candidates_list <- lapply(
    candidates_list,
    \(x) x[!is.na(fastmatch::fmatch(x, attached_pkgs))]
  )

  has_candidates <- lengths(candidates_list) > 0
  if (!any(has_candidates)) {
    return(empty)
  }

  idx <- unqual$idx[has_candidates]
  funs <- unqual$funs[has_candidates]
  candidates_list <- candidates_list[has_candidates]

  origins_list <- Map(
    function(cands, fun) {
      origins <- vapply(
        cands,
        .origin_pkg,
        character(1),
        fun = fun,
        origin_map = origin_map
      )
      origins[!is.na(fastmatch::fmatch(origins, allowed_packages))]
    },
    candidates_list,
    funs
  )

  has_origins <- lengths(origins_list) > 0L
  if (!any(has_origins)) {
    return(empty)
  }

  idx <- idx[has_origins]
  funs <- funs[has_origins]
  candidates_list <- candidates_list[has_origins]
  origins_list <- origins_list[has_origins]

  origin_candidates <- lapply(origins_list, unique)

  is_ambiguous <- lengths(origin_candidates) > 1

  pkgs <- character()
  keys <- character()
  ambiguous <- character()

  if (!all(is_ambiguous)) {
    best_pkgs0 <- unlist(origin_candidates[!is_ambiguous], use.names = FALSE)
    funs0 <- funs[!is_ambiguous]
    pkgs <- c(pkgs, best_pkgs0)
    keys <- c(keys, paste0(best_pkgs0, "::", funs0))
  }

  if (any(is_ambiguous)) {
    ambig_idx <- idx[is_ambiguous]
    ambig_funs <- funs[is_ambiguous]
    ambig_cands <- candidates_list[is_ambiguous]
    intervals <- findInterval(ambig_idx, attached_visit_idx)
    resolved <- logical(length(ambig_idx))

    for (i in seq_along(ambig_idx)) {
      k <- intervals[i]
      cands <- ambig_cands[[i]]

      if (k == 0) {
        resolved[i] <- FALSE
      } else {
        attached_before <- attached_pkgs[seq_len(k)]
        matches <- fastmatch::fmatch(cands, attached_before)
        if (all(is.na(matches))) {
          resolved[i] <- FALSE
        } else {
          pkg <- cands[which.max(ifelse(is.na(matches), -1L, matches))]
          resolved[i] <- TRUE
        }
      }

      if (resolved[i]) {
        origin <- .resolve_origin_pkg(
          pkg,
          ambig_funs[i],
          origin_map,
          allowed_packages
        )
        pkgs <- c(pkgs, origin)
        keys <- c(keys, paste0(origin, "::", ambig_funs[i]))
      }
    }

    ambiguous <- sort(unique(ambig_funs[!resolved]))
  }

  list(pkgs = pkgs, keys = keys, ambiguous = ambiguous)
}

#' Ignored functions/directories used by scanner
#'
#' @name internal_data
#' @rdname internal_data
#' @keywords internal
NULL

#' Default ignored functions
#'
#' Vector of functions to be ignored when parsing.
#' Generated in `data-raw/sysdata.R` from exports of base R packages.
#'
#' @rdname internal_data
#' @export
#' @examples
#' head(stdlib_funs())
stdlib_funs <- function() {
  # lapply(
  #   c("base", "stats", "utils", "graphics", "grDevices", "methods"),
  #   getNamespaceExports
  # ) |>
  #   unlist(use.names = FALSE) |>
  #   unique() |>
  #   sort()
  .stdlib_funs
}

#' Default skip directories
#'
#' Vector of directories skipped when recursively searching
#' a project. Generated in `data-raw/sysdata.R`.
#'
#' @rdname internal_data
#' @export
#' @examples
#' scan_skip_dirs()
scan_skip_dirs <- function() {
  # c(
  #   "renv",
  #   "packrat",
  #   "rv",
  #   ".Rcheck",
  #   "revdep",
  #   "_site",
  #   "_book",
  #   "_bookdown_files",
  #   "_freeze",
  #   ".quarto",
  #   ".quarto_cache",
  #   ".knitr_cache",
  #   "_cache",
  #   ".cache"
  # )
  .scan_skip_dirs
}
