#' Find used Functions and Packages
#'
#' The Stan values for `allowed_packages`, `export_index`, and `origin_map`
#' are generated by `data_raw/sysdata.R`.
#'
#' Unqualified function calls are only attributed when a Stan package is
#' attached via `library()` or `require()` in the same file. Known reexports
#' are remapped to their origin packages; missing mappings fall back to the
#' resolved package.
#'
#' @inheritParams stan_cite
#' @param allowed_packages Character vector of package namespaces to attribute
#'   to Stan usage. Defaults to `.stan_pkgs`.
#' @param export_index Named list mapping function names to packages. Defaults
#'   to `.stan_export_index`.
#' @param origin_map Named character vector mapping `pkg::fun` keys to the
#'   origin package. Defaults to `.stan_origin_map`.
#' @param skip_dirs Character vector of directory names to skip when scanning a
#'   directory. Defaults to `.scan_skip_dirs`.
#' @return A list of packages, resolved functions, and ambiguous function calls.
#' @export
scan_usage <- function(
  path = ".",
  ignore_unqualified_functions = .stdlib_funs,
  strict = FALSE,
  skip_dirs = .scan_skip_dirs,
  allowed_packages = .stan_pkgs,
  export_index = .stan_export_index,
  origin_map = .stan_origin_map
) {
  paths <- normalizePath(path, winslash = "/", mustWork = TRUE)
  dir_flags <- dir.exists(paths)

  files <- if (length(paths) == 1L && dir_flags) {
    dir_path <- paths[[1L]]
    cli::cli_alert_info("Searching directory {.path {dir_path}}")
    list.files(
      dir_path,
      recursive = TRUE,
      full.names = TRUE,
      ignore.case = TRUE,
      pattern = "\\.(R|Rmd|Qmd)$"
    ) |>
      normalizePath(winslash = "/", mustWork = FALSE) |>
      (\(paths) {
        if (!length(skip_dirs)) {
          return(paths)
        }
        skip_regex <- .scan_skip_regex(skip_dirs)
        paths[!grepl(skip_regex, paths)]
      })()
  } else {
    if (any(dir_flags)) {
      cli::cli_abort(c(
        "{.arg path} must be a single directory or a vector of files.",
        "x" = "Mixed directories and files or multiple directories are not supported."
      ))
    }
    paths |>
      (\(paths) {
        lapply(
          paths,
          \(file_path) cli::cli_alert_info("Searching {.path {file_path}}")
        )
        paths
      })()
  }

  if (!length(files)) {
    cli::cli_abort(c(
      "No files found.",
      "i" = "Check the {.arg path} and {.arg skip_dirs} arguments."
    ))
  }

  hits <- unique(files) |>
    lapply(
      \(file) {
        file |>
          .extract_code() |>
          .scan_tokens(
            ignore_unqualified_functions = ignore_unqualified_functions,
            strict = strict,
            allowed_packages = allowed_packages,
            export_index = export_index,
            origin_map = origin_map,
            file_path = file
          )
      }
    )

  ambiguous <- .collect_unique(hits, "ambiguous")
  if (length(ambiguous)) {
    funs <- cli::cli_vec(ambiguous)

    msg <- c(
      "Cannot reliably detect which packages some functions are from.",
      "x" = paste0(
        "Ambiguous functions: ",
        paste0("{.fun ", ambiguous, "}", collapse = ", ")
      ),
      "i" = "Please namespace them ({.code pkg::function()}) and rerun or set {.code strict = FALSE}."
    )

    if (strict) cli::cli_abort(msg) else cli::cli_warn(msg)
  }

  structure(
    list(
      packages = .collect_unique(hits, "pkgs"),
      functions = .collect_unique(hits, "keys"),
      ambiguous = ambiguous
    ),
    class = "scan_usage"
  )
}

.scan_skip_regex <- function(skip_dirs) {
  escaped <- vapply(
    skip_dirs,
    \(x) gsub("([][{}()+*^$|\\\\.?])", "\\\\\\1", x),
    character(1)
  )
  paste0("(^|/)(?:", paste(escaped, collapse = "|"), ")(/|$)")
}

.collect_unique <- function(hits, field) {
  hits |>
    lapply(`[[`, field) |>
    unlist(use.names = FALSE) |>
    unique() |>
    sort()
}

.extract_code <- function(file) {
  ext <- file |>
    sub(".*\\.", "", x = _) |>
    tolower()

  if (!ext %in% c("r", "rmd", "qmd")) {
    cli::cli_abort(c(
      "Unsupported file extension: {.val {ext}}.",
      "i" = "Supported extensions are {.file .R}, {.file .Rmd}, and {.file .qmd}."
    ))
  }

  if (identical(ext, "r")) {
    return(paste(readLines(file, warn = FALSE), collapse = "\n"))
  }

  tmp <- tempfile(fileext = ".R")
  on.exit(unlink(tmp), add = TRUE)

  if (identical(ext, "rmd") || identical(ext, "qmd")) {
    if (!requireNamespace("knitr", quietly = TRUE)) {
      cli::cli_abort(c(
        "Package {.pkg knitr} is required to parse R Markdown ({.file .Rmd}) or Quarto ({.file .qmd}) files.",
        "i" = "Please install it with {.code install.packages('knitr')}."
      ))
    }
    knitr::purl(file, tmp, quiet = TRUE, documentation = 0)
  }

  paste(readLines(tmp, warn = FALSE), collapse = "\n")
}

.scan_tokens <- function(
  code,
  ignore_unqualified_functions,
  strict = FALSE,
  allowed_packages = .stan_pkgs,
  export_index = .stan_export_index,
  origin_map = .stan_origin_map,
  file_path = NULL
) {
  empty <- list(pkgs = character(), keys = character(), ambiguous = character())
  expr <- tryCatch(
    parse(text = code, keep.source = FALSE),
    error = function(e) NULL
  )
  if (is.null(expr)) {
    path_label <- if (!is.null(file_path) && nzchar(file_path)) {
      file_path
    } else {
      "<unknown file>"
    }
    msg <- c(
      "Failed to parse {.path {path_label}}.",
      "x" = "Syntax error in file."
    )
    if (strict) {
      cli::cli_abort(msg)
    } else {
      cli::cli_warn(msg)
    }
    return(empty)
  }

  acc <- new.env(parent = emptyenv())
  acc$visit_idx <- 0L
  acc$lib_pkgs <- character()
  acc$lib_visit_idx <- integer()
  acc$lib_is_attach <- logical()
  acc$ns_pkgs <- character()
  acc$ns_keys <- character()
  acc$unqual_funs <- character()
  acc$unqual_visit_idx <- integer()

  lib_funs <- c("library", "require", "requireNamespace")
  ns_ops <- c("::", ":::")
  use_heads <- c("c", "list")
  ignore_heads <- c(
    "if",
    "for",
    "while",
    "repeat",
    "function",
    "return",
    "next",
    "break",
    "{",
    "(",
    "<-",
    "<<-",
    "->",
    "->>",
    "=",
    "+",
    "-",
    "*",
    "/",
    "^",
    "%%",
    "%/%",
    "%*%",
    "%>%",
    ":",
    "|",
    "&",
    "||",
    "&&",
    "!",
    "~",
    "|>",
    "$",
    "@",
    "[",
    "[["
  )

  for (i in seq_along(expr)) {
    .ast_walk(
      expr[[i]],
      acc,
      ignore_unqualified_functions,
      lib_funs,
      allowed_packages,
      ns_ops,
      use_heads,
      ignore_heads
    )
  }

  lib_data <- if (length(acc$lib_pkgs)) {
    data.frame(
      visit_idx = acc$lib_visit_idx,
      pkg = acc$lib_pkgs,
      is_attach = acc$lib_is_attach,
      stringsAsFactors = FALSE
    )
  } else {
    NULL
  }

  resolved <- .resolve_candidates(
    list(funs = acc$unqual_funs, idx = acc$unqual_visit_idx),
    lib_data,
    strict,
    allowed_packages,
    export_index,
    origin_map
  )

  list(
    pkgs = c(acc$lib_pkgs, acc$ns_pkgs, resolved$pkgs),
    keys = c(acc$ns_keys, resolved$keys),
    ambiguous = resolved$ambiguous
  )
}

.ast_walk <- function(
  x,
  acc,
  ignore_unqualified_functions,
  lib_funs,
  allowed_packages,
  ns_ops,
  use_heads,
  ignore_heads
) {
  if (is.null(x)) {
    return(invisible(NULL))
  }

  if (is.call(x)) {
    acc$visit_idx <- acc$visit_idx + 1L

    head <- x[[1L]]
    head_name <- if (is.symbol(head)) as.character(head) else NULL

    if (!is.null(head_name)) {
      if (!is.na(fastmatch::fmatch(head_name, ns_ops)) && length(x) >= 3L) {
        pkg <- .ast_lit_name(x[[2L]])
        fun <- .ast_lit_name(x[[3L]])
        if (
          !is.null(pkg) &&
            !is.null(fun) &&
            !is.na(fastmatch::fmatch(pkg, allowed_packages))
        ) {
          acc$ns_pkgs <- c(acc$ns_pkgs, pkg)
          acc$ns_keys <- c(acc$ns_keys, paste0(pkg, "::", fun))
        }
      } else if (identical(head_name, "use")) {
        pkg <- .ast_get_lib_pkg(x)
        if (!is.null(pkg) && !is.na(fastmatch::fmatch(pkg, allowed_packages))) {
          acc$ns_pkgs <- c(acc$ns_pkgs, pkg)
          funs <- .ast_get_use_funs(x, use_heads)
          if (length(funs)) {
            acc$ns_keys <- c(acc$ns_keys, paste0(pkg, "::", funs))
          }
        }
      } else if (!is.na(fastmatch::fmatch(head_name, lib_funs))) {
        pkg <- .ast_get_lib_pkg(x)
        if (!is.null(pkg) && !is.na(fastmatch::fmatch(pkg, allowed_packages))) {
          acc$lib_pkgs <- c(acc$lib_pkgs, pkg)
          acc$lib_visit_idx <- c(acc$lib_visit_idx, acc$visit_idx)
          acc$lib_is_attach <- c(
            acc$lib_is_attach,
            !identical(head_name, "requireNamespace")
          )
        }
      } else if (!is.na(fastmatch::fmatch(head_name, ignore_heads))) {
        # Skip language keywords, operators, and subsetting.
      } else if (
        is.na(fastmatch::fmatch(head_name, ignore_unqualified_functions))
      ) {
        acc$unqual_funs <- c(acc$unqual_funs, head_name)
        acc$unqual_visit_idx <- c(acc$unqual_visit_idx, acc$visit_idx)
      }
    }

    if (is.call(head)) {
      .ast_walk(
        head,
        acc,
        ignore_unqualified_functions,
        lib_funs,
        allowed_packages,
        ns_ops,
        use_heads,
        ignore_heads
      )
    }
    n <- length(x)
    if (n >= 2L) {
      for (i in 2L:n) {
        .ast_walk(
          x[[i]],
          acc,
          ignore_unqualified_functions,
          lib_funs,
          allowed_packages,
          ns_ops,
          use_heads,
          ignore_heads
        )
      }
    }
    return(invisible(NULL))
  }

  if (is.expression(x)) {
    for (i in seq_along(x)) {
      .ast_walk(
        x[[i]],
        acc,
        ignore_unqualified_functions,
        lib_funs,
        allowed_packages,
        ns_ops,
        use_heads,
        ignore_heads
      )
    }
    return(invisible(NULL))
  }

  if (is.pairlist(x) || is.list(x)) {
    for (i in seq_along(x)) {
      .ast_walk(
        x[[i]],
        acc,
        ignore_unqualified_functions,
        lib_funs,
        allowed_packages,
        ns_ops,
        use_heads,
        ignore_heads
      )
    }
    return(invisible(NULL))
  }

  invisible(NULL)
}

.ast_lit_name <- function(x) {
  if (is.symbol(x)) {
    return(as.character(x))
  }
  if (is.character(x) && length(x) == 1L) {
    return(x)
  }
  NULL
}

.ast_get_lib_pkg <- function(call) {
  args <- as.list(call)[-1L]
  if (!length(args)) {
    return(NULL)
  }

  nms <- names(args)
  pkg_i <- if (!is.null(nms)) fastmatch::fmatch("package", nms) else NA_integer_
  pkg_j <- if (!is.null(nms)) fastmatch::fmatch("pkg", nms) else NA_integer_

  arg <- if (!is.na(pkg_i)) {
    args[[pkg_i]]
  } else if (!is.na(pkg_j)) {
    args[[pkg_j]]
  } else {
    args[[1L]]
  }

  .ast_lit_name(arg)
}

.ast_collect_use_funs <- function(x, use_heads) {
  if (is.null(x)) {
    return(character())
  }

  lit <- .ast_lit_name(x)
  if (!is.null(lit)) {
    return(lit)
  }

  if (is.call(x)) {
    head <- x[[1L]]
    head_name <- if (is.symbol(head)) as.character(head) else NULL
    if (
      !is.null(head_name) && !is.na(fastmatch::fmatch(head_name, use_heads))
    ) {
      funs <- character()
      if (length(x) >= 2L) {
        for (i in 2L:length(x)) {
          funs <- c(funs, .ast_collect_use_funs(x[[i]], use_heads))
        }
      }
      return(funs)
    }
  }

  character()
}

.ast_get_use_funs <- function(call, use_heads) {
  args <- as.list(call)[-1L]
  if (length(args) <= 1L) {
    return(character())
  }

  nms <- names(args)
  pkg_i <- if (!is.null(nms)) fastmatch::fmatch("pkg", nms) else NA_integer_
  pkg_j <- if (!is.null(nms)) fastmatch::fmatch("package", nms) else NA_integer_

  pkg_idx <- if (!is.na(pkg_i)) {
    pkg_i
  } else if (!is.na(pkg_j)) {
    pkg_j
  } else {
    1L
  }

  fun_args <- args[-pkg_idx]
  funs <- unlist(
    lapply(fun_args, .ast_collect_use_funs, use_heads = use_heads),
    use.names = FALSE
  )
  funs[nzchar(funs)]
}

.resolve_candidates <- function(
  unqual,
  lib_data,
  strict,
  allowed_packages = .stan_pkgs,
  export_index = .stan_export_index,
  origin_map = .stan_origin_map
) {
  empty <- list(pkgs = character(), keys = character(), ambiguous = character())
  if (!length(unqual$funs) || !length(allowed_packages)) {
    return(empty)
  }

  attached_pkgs <- character()
  attached_visit_idx <- integer()
  if (!is.null(lib_data) && any(lib_data$is_attach)) {
    attached_pkgs <- lib_data$pkg[lib_data$is_attach]
    attached_visit_idx <- lib_data$visit_idx[lib_data$is_attach]
  }
  if (!length(attached_pkgs)) {
    return(empty)
  }

  candidates_list <- export_index[unqual$funs] |>
    lapply(\(x) x[!is.na(fastmatch::fmatch(x, allowed_packages))])
  candidates_list <- lapply(
    candidates_list,
    \(x) x[!is.na(fastmatch::fmatch(x, attached_pkgs))]
  )

  has_candidates <- lengths(candidates_list) > 0
  if (!any(has_candidates)) {
    return(empty)
  }

  idx <- unqual$idx[has_candidates]
  funs <- unqual$funs[has_candidates]
  candidates_list <- candidates_list[has_candidates]

  is_ambiguous <- lengths(candidates_list) > 1

  pkgs <- character()
  keys <- character()
  ambiguous <- character()

  if (!all(is_ambiguous)) {
    best_pkgs0 <- unlist(candidates_list[!is_ambiguous], use.names = FALSE)
    funs0 <- funs[!is_ambiguous]
    keys0 <- paste0(best_pkgs0, "::", funs0)

    origin0 <- unname(origin_map[keys0])
    origin0[is.na(origin0)] <- best_pkgs0[is.na(origin0)]

    keep <- !is.na(fastmatch::fmatch(origin0, allowed_packages))
    if (any(keep)) {
      pkgs <- c(pkgs, origin0[keep])
      keys <- c(keys, paste0(origin0[keep], "::", funs0[keep]))
    }
  }

  if (any(is_ambiguous)) {
    ambig_idx <- idx[is_ambiguous]
    ambig_funs <- funs[is_ambiguous]
    ambig_cands <- candidates_list[is_ambiguous]
    ambiguous <- sort(unique(ambig_funs))

    if (!strict) {
      intervals <- findInterval(ambig_idx, attached_visit_idx)
      resolved <- logical(length(ambig_idx))

      for (i in seq_along(ambig_idx)) {
        k <- intervals[i]
        cands <- ambig_cands[[i]]

        if (k == 0) {
          resolved[i] <- FALSE
        } else {
          attached_before <- attached_pkgs[seq_len(k)]
          matches <- fastmatch::fmatch(cands, attached_before)
          if (all(is.na(matches))) {
            resolved[i] <- FALSE
          } else {
            pkg <- cands[which.max(ifelse(is.na(matches), -1L, matches))]
            resolved[i] <- TRUE
          }
        }

        if (resolved[i]) {
          key <- paste0(pkg, "::", ambig_funs[i])
          origin <- unname(origin_map[key])
          if (
            is.na(origin) || is.na(fastmatch::fmatch(origin, allowed_packages))
          ) {
            origin <- pkg
          }

          pkgs <- c(pkgs, origin)
          keys <- c(keys, paste0(origin, "::", ambig_funs[i]))
        }
      }

      if (length(ambiguous)) {
        ambiguous <- setdiff(ambiguous, unique(ambig_funs[resolved]))
      }
    }
  }

  list(pkgs = pkgs, keys = keys, ambiguous = ambiguous)
}

#' Standard-library function names to never attribute to Stan packages
#'
#' This includes exports from: base, stats, utils, graphics, grDevices, methods.
#' This is generated in `data_raw/sysdata.R` and exported for documentation/transparency.
#'
#' @return Character vector of standard-library function names.
#' @export
stdlib_funs <- function() {
  # lapply(
  #   c("base", "stats", "utils", "graphics", "grDevices", "methods"),
  #   getNamespaceExports
  # ) |>
  #   unlist(use.names = FALSE) |>
  #   unique() |>
  #   sort()
  .stdlib_funs
}

#' Default directory names skipped by scan_usage/stan_cite
#' @return Character vector of directory names to skip.
#' @keywords internal
scan_skip_dirs <- function() {
  # c(
  #   "renv",
  #   "packrat",
  #   "rv",
  #   ".Rcheck",
  #   "revdep",
  #   "_site",
  #   "_book",
  #   "_bookdown_files",
  #   "_freeze",
  #   ".quarto",
  #   ".quarto_cache",
  #   ".knitr_cache",
  #   "_cache",
  #   ".cache"
  # )
  .scan_skip_dirs
}
