name: Continuous Benchmarks (Receive)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      # Run benchmarks when files related to cite or funscanr are changed
      - "R/aaa.R"
      - "R/citation.R"
      - "R/funscanr.R"
      - "data-raw/sysdata.R"
      - "data-raw/**citations.R"
      # Benchmarking config and scripts
      - "touchstone/**"
      # Workflow configuration
      - ".github/workflows/touchstone-*.yaml"
      # Package metadata
      - "DESCRIPTION"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.read_touchstone_config.outputs.config }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: read_touchstone_config
        run: |
          echo "config=$(cat ./touchstone/config.json | jq -c .)" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - ${{ fromJson(needs.prepare.outputs.config) }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: lorenzwalthert/touchstone/actions/receive@main
        with:
          cache-version: 1
