name: Continuous Benchmarks (Receive)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      # Run benchmarks when files related to cite or funscanr are changed
      - "R/aaa.R"
      - "R/citation.R"
      - "R/funscanr.R"
      - "data-raw/sysdata.R"
      - "data-raw/**citations.R"
      # Benchmarking config and scripts
      - "touchstone/**"
      # Workflow configuration
      - ".github/workflows/touchstone-*.yaml"
      # Package metadata
      - "DESCRIPTION"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.read_touchstone_config.outputs.config }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: read_touchstone_config
        run: |
          echo "config=$(cat ./touchstone/config.json | jq -c .)" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - ${{ fromJson(needs.prepare.outputs.config) }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      R_REPOS: https://production.r-multiverse.org/2025-12-15,${{ matrix.config.rspm }}
      RENV_CONFIG_REPOS_OVERRIDE: https://production.r-multiverse.org/2025-12-15,${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: false

      - name: Pin repos for pak
        run: |
          cat > .github/touchstone.Rprofile <<'EOF'
          options(
            repos = c(
              Multiverse = "https://production.r-multiverse.org/2025-12-15",
              CRAN = "https://packagemanager.posit.co/cran/2025-10-15"
            ),
            pkg.use_bioconductor = FALSE
          )
          EOF
          echo "R_PROFILE_USER=$PWD/.github/touchstone.Rprofile" >> $GITHUB_ENV

      - name: Install pak
        run: |
          R -q -e 'install.packages("pak")'

      - name: Install package dependencies
        run: |
          R -q -e 'pak::pkg_install(c("deps::.", "github::lorenzwalthert/touchstone@v1"), dependencies = "hard")'

      - name: Run touchstone
        run: |
          Rscript -e 'touchstone::run_script("touchstone/script.R")'
